name: Send Daily English Questions

on:
  schedule:
    # Runs at 20:12 IST (14:42 UTC) every day
    - cron: '42 14 * * *'
  workflow_dispatch: # Allows manual running from the Actions tab

jobs:
  permissions:
    contents: write
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      run: python main.py

    - name: Commit progress file
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions-bot@github.com'
        git add progress.txt
        # Commit only if there are changes
        git diff --staged --quiet || git commit -m "Update word progress"
        git push
